### ISSUE TITLE
Exposing DocumentError

### ISSUE THREAD

**Issue by hwchen** [yggie/rust-xml-query#2]
Hello,

Sorry if I missed something obvious (still relatively new to rust), but it looks like `DocumentError` is not exposed for public use.

I'm trying to implement a `From` for error handling in my own library. If you know a better way for me to handle the error from `Document::new_from_xml_stream`, please let me know.

**Comment by yggie** [comment]
@hwchen you are absolutely right, `DocumentError` was not exposed publicly and that wasn’t my intention! If you update the library to the latest version, it should have the `enum` exposed now.

**Comment by hwchen** [comment]
Thanks a bunch!
