### ISSUE TITLE
Exposing Element node_index

### ISSUE THREAD

**Issue by ancamcheachta** [yggie/rust-xml-query#5]
I currently have an use case in which I'd like to filter an iterator of elements that fall inside a range of node indices.  As of 0.3.2 however, `node_index` is a private field, and I couldn't find an existing public function that returns it.

My proposed solution is an additional function of the same name, 
```rust
pub fn node_index(&self) -> usize
```

 Currently I have a [working example](https://github.com/ancamcheachta/rquery/tree/node-index) with a test to cover.  In this case, I thought the sane thing to would be to [follow precedent](https://github.com/yggie/rquery/blob/f5a1a84661da9bd8f0500e97a0f2d6b25b479b56/src/lib.rs#L181)  where, for example, the `text` field was exposed via a `text()` function.

That sound okay @yggie ?

PR: https://github.com/yggie/rquery/pull/6

**Comment by yggie** [comment]
@ancamcheachta that all looks great, I took the liberty of bumping the version published on crates.io to include the changes you introduced, let me know if this solves your use case.

**Comment by ancamcheachta** [comment]
@yggie indeed, that's solved.  Thanks for that!

On a separate note, it seems to me the documentation page linked in the crate (https://yggie.github.io/rquery/rquery) is frozen on 0.2.0.  Is that deliberate?  If not I can open new issue/PR.  docs.rs would appear to have [the latest](https://docs.rs/rquery)

**Comment by yggie** [comment]
@ancamcheachta nope that isn’t deliberate, I will update that shortly
